[general]
  case_insensitive      = true   # whether or not to be case insensitive
  max_messages          = 2500   # max amount of messages to fetch
  offline_members       = true   # whether or not to cache offline members
  heartbeat_timeout     = 30     # heatbeat timeout in seconds
  token                 = ""     # token used to connect to the discord bot api

[network]

    [network.spotify]
    client_id      = ""          # spotify api client id
    client_secret  = ""          # spotify api client secret
