[general]

  [general.bot]
  case_insensitive   = true   # whether or not to be case insensitive
  max_messages       = 2500   # max amount of messages to fetch
  offline_members    = true   # whether or not to cache offline members
  heartbeat_timeout  = 30     # heatbeat timeout in seconds
  owners             = []     # the owners of the bot
  prefixes           = []     # prefixes recgonizable by the bot
  debug              = false  # whether or not debug mode is enabled

  [general.api]
  token              = ""
